apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: feed
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: feed
  minReplicas: 1
  maxReplicas: 10
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 50
status:
  observedGeneration: 1
  lastScaleTime: 3
  currentReplicas: 1
  desiredReplicas: 1
  currentMetrics:
  - type: Resource
    resource:
      name: cpu
      current:
        averageUtilization: 0
        averageValue: 0
